language: node_js

node_js: node

cache: npm

install:
    - npm install -g yarn
    - yarn install --non-interactive
    
script:
    - npx node-sass --output-style compressed --source-map true --follow --output src src
    - npx sassdoc src
