language: node_js

node_js: node

cache: npm

install:
    - npm install --global yarn
    - yarn install --non-interactive --production false
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin
    
script:
    - sassdoc src
    - node-sass --follow --output src src
    - postcss src/ros-css-styles-toolkit.css --map --replace

